version: '3.9'

services:
  web:
    build:
      context: ./services/app
      dockerfile: Dockerfile.prod
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/static
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:13.2-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./services/nginx
    ports:
      - 1337:80
    volumes:
      - static_volume:/home/app/web/static
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: